# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'bogus/rspec'

# In order to test sing celluloid and bogus it is neccessary to
# ensure the following Method methods are available.
# https://github.com/psyho/bogus/issues/24
module Celluloid
  class Method
    def name
      @proxy.method_missing(:method, @name).name
    end

    def parameters
      @proxy.method_missing(:method, @name).parameters
    end

    def to_proc
      @proxy.method_missing(:method, @name).to_proc
    end
  end
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
#  config.mock_framework = :rr
end
